export enum StandingType {
  FINAL = "FINAL",
  GROUP_A = "GROUP_A",
  GROUP_B = "GROUP_B",
  GROUP_C = "GROUP_C",
  REGULAR = "REGULAR",
  PLAYOFF = "PLAYOFF",
  FINAL_TOURNAMENT = "FINAL_TOURNAMENT",
  UNKNOWN = "UNKNOWN",
  WEST = "WEST",
  EAST = "EAST",
  MIDDLE = "MIDDLE",
}
